// Chợ Phú Thọ - nhắn tin người mua/người bán
(function(){
  const esc=v=>typeof escapeHtml==='function'?escapeHtml(v):String(v??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#039;','"':'&quot;'}[c]));
  const qs=new URLSearchParams(location.search);
  const targetId=qs.get('seller')||qs.get('user');
  const listingId=qs.get('listing');
  let me=null, activeUser=targetId, activeListing=listingId, pollTimer=null;
  async function init(){
    if(typeof supabaseClient==='undefined') return;
    me=(await supabaseClient.auth.getUser()).data?.user||null;
    const shell=document.getElementById('chatShell');
    if(!me){shell.innerHTML='<div class="empty-state"><h3>Đăng nhập để nhắn tin</h3><p>Trao đổi trực tiếp với người mua hoặc người bán.</p><a class="primary-button" href="dang-nhap.html?next=chat.html">Đăng nhập</a></div>';return;}
    renderShell(); await loadConversations(); if(activeUser) await loadThread(activeUser,activeListing); pollTimer=setInterval(()=>activeUser&&loadThread(activeUser,activeListing),7000);
  }
  function renderShell(){document.getElementById('chatShell').innerHTML='<aside class="chat-list"><div class="chat-list-head"><strong>Hội thoại</strong><button id="chatRefresh" type="button">↻</button></div><div id="conversationList"><div class="loading">Đang tải...</div></div></aside><section class="chat-main"><div id="chatHeader" class="chat-header">Chọn một cuộc trò chuyện</div><div id="messageList" class="message-list"><div class="empty-state"><p>Chọn hội thoại để bắt đầu.</p></div></div><form id="messageForm" class="message-form"><input id="messageInput" maxlength="1000" placeholder="Nhập tin nhắn..." autocomplete="off"><button type="submit">Gửi</button></form></section>';document.getElementById('chatRefresh').onclick=loadConversations;document.getElementById('messageForm').onsubmit=sendMessage;}
  async function loadConversations(){const box=document.getElementById('conversationList');if(!box)return;const {data,error}=await supabaseClient.from('messages').select('id,listing_id,sender_id,receiver_id,body,created_at,read_at').or(`sender_id.eq.${me.id},receiver_id.eq.${me.id}`).order('created_at',{ascending:false}).limit(100);if(error){box.innerHTML='<div class="empty-state"><p>Không tải được hội thoại.</p></div>';return;}const map=new Map();for(const m of data||[]){const other=m.sender_id===me.id?m.receiver_id:m.sender_id;const key=`${other}:${m.listing_id||''}`;if(!map.has(key))map.set(key,m);}const ids=[...new Set([...map.values()].map(m=>m.sender_id===me.id?m.receiver_id:m.sender_id))];let names={};if(ids.length){const r=await supabaseClient.from('profiles').select('id,full_name,shop_name').in('id',ids);for(const p of r.data||[])names[p.id]=p.shop_name||p.full_name||'Người dùng';}if(!map.size){box.innerHTML='<div class="empty-state"><p>Chưa có cuộc trò chuyện.</p></div>';return;}box.innerHTML=[...map.entries()].map(([key,m])=>{const other=m.sender_id===me.id?m.receiver_id:m.sender_id;return `<button class="conversation-item ${other===activeUser&&String(m.listing_id||'')===String(activeListing||'')?'active':''}" data-user="${esc(other)}" data-listing="${esc(m.listing_id||'')}"><strong>${esc(names[other]||'Người dùng')}</strong><span>${esc(m.body||'')}</span><small>${new Date(m.created_at).toLocaleString('vi-VN',{day:'2-digit',month:'2-digit',hour:'2-digit',minute:'2-digit'})}</small></button>`}).join('');box.querySelectorAll('.conversation-item').forEach(b=>b.onclick=()=>{activeUser=b.dataset.user;activeListing=b.dataset.listing||null;loadConversations();loadThread(activeUser,activeListing);});}
  async function loadThread(userId,lid){const {data,error}=await supabaseClient.from('messages').select('id,listing_id,sender_id,receiver_id,body,created_at,read_at').or(`and(sender_id.eq.${me.id},receiver_id.eq.${userId}),and(sender_id.eq.${userId},receiver_id.eq.${me.id})`).order('created_at',{ascending:true});if(error)return;const rows=(data||[]).filter(m=>!lid||String(m.listing_id||'')===String(lid));const prof=await supabaseClient.from('profiles').select('full_name,shop_name').eq('id',userId).maybeSingle();document.getElementById('chatHeader').innerHTML=`<strong>${esc(prof.data?.shop_name||prof.data?.full_name||'Người dùng')}</strong>${lid?`<a href="chi-tiet.html?id=${encodeURIComponent(lid)}">Xem tin đăng</a>`:''}`;const box=document.getElementById('messageList');box.innerHTML=rows.length?rows.map(m=>`<div class="message-row ${m.sender_id===me.id?'mine':''}"><div class="message-bubble">${esc(m.body).replace(/\n/g,'<br>')}<small>${new Date(m.created_at).toLocaleTimeString('vi-VN',{hour:'2-digit',minute:'2-digit'})}</small></div></div>`).join(''):'<div class="empty-state"><p>Hãy gửi lời chào đầu tiên.</p></div>';box.scrollTop=box.scrollHeight;await supabaseClient.from('messages').update({read_at:new Date().toISOString()}).eq('receiver_id',me.id).eq('sender_id',userId).is('read_at',null);}
  async function sendMessage(e){e.preventDefault();if(!activeUser){alert('Hãy chọn một cuộc trò chuyện.');return;}const input=document.getElementById('messageInput'),body=input.value.trim();if(!body)return;const {error}=await supabaseClient.from('messages').insert({sender_id:me.id,receiver_id:activeUser,listing_id:activeListing?Number(activeListing):null,body});if(error){alert('Không thể gửi tin nhắn: '+error.message);return;}input.value='';await loadThread(activeUser,activeListing);await loadConversations();}
  window.addEventListener('beforeunload',()=>pollTimer&&clearInterval(pollTimer));document.addEventListener('DOMContentLoaded',init);
})();