(function(){
  function injectStyle(){
    if(document.getElementById('location-fix-style'))return;
    const s=document.createElement('style');s.id='location-fix-style';s.textContent='.location-modal{pointer-events:none}.location-modal.open{pointer-events:auto}.location-backdrop{z-index:0;pointer-events:auto}.location-dialog{z-index:2;pointer-events:auto;touch-action:manipulation}.location-dialog button,.location-dialog select{position:relative;z-index:3;pointer-events:auto;touch-action:manipulation}';document.head.appendChild(s);
  }
  function openModal(){const m=document.getElementById('locationModal');if(!m)return;m.setAttribute('aria-hidden','false');m.classList.add('open');const b=document.getElementById('allowLocation');if(b)b.focus({preventScroll:true});}
  function closeModal(){const m=document.getElementById('locationModal');if(!m)return;m.setAttribute('aria-hidden','true');m.classList.remove('open');}
  function setArea(area){if(typeof window.setSelectedLocation==='function')window.setSelectedLocation(area);else{localStorage.setItem('choPhuThoLocation',area);const t=document.getElementById('selectedLocation'),s=document.getElementById('locationStatus');if(t)t.textContent=area||'Chọn khu vực';if(s)s.textContent=area?'Đang ưu tiên tin và dịch vụ tại '+area+'.':'Chưa chọn khu vực. Bạn có thể chọn khu vực thủ công hoặc cho phép GPS.';}}
  function detect(){const manual=document.getElementById('manualLocationBox');if(!window.isSecureContext){alert('Trang web cần HTTPS để dùng GPS. Bạn vẫn có thể chọn khu vực thủ công.');manual?.removeAttribute('hidden');return}if(!navigator.geolocation){alert('Trình duyệt không hỗ trợ GPS. Bạn có thể chọn khu vực thủ công.');manual?.removeAttribute('hidden');return}const b=document.getElementById('allowLocation');if(b){b.disabled=true;b.textContent='📍 Đang lấy vị trí...'}navigator.geolocation.getCurrentPosition(p=>{localStorage.setItem('choPhuThoLat',String(p.coords.latitude));localStorage.setItem('choPhuThoLng',String(p.coords.longitude));localStorage.setItem('choPhuThoLocationSource','gps');const current=localStorage.getItem('choPhuThoLocation')||'';setArea(current||'Vị trí hiện tại');closeModal();if(typeof window.applyHomeFilters==='function')window.applyHomeFilters()},e=>{console.warn('Geolocation error',e);if(e?.code===1)alert('Trình duyệt đang chặn quyền vị trí. Hãy bấm biểu tượng ổ khóa cạnh địa chỉ website → Vị trí → Cho phép, sau đó thử lại.');else alert('Chưa lấy được vị trí. Bạn có thể chọn khu vực thủ công.');manual?.removeAttribute('hidden');if(b){b.disabled=false;b.textContent='📍 Cho phép vị trí GPS'}},{enableHighAccuracy:true,timeout:15000,maximumAge:60000});setTimeout(()=>{if(b){b.disabled=false;b.textContent='📍 Cho phép vị trí GPS'}},16000)}
  function init(){injectStyle();window.openLocationModal=openModal;window.closeLocationModal=closeModal;window.detectLocation=detect;const saved=localStorage.getItem('choPhuThoLocation')||'';if(typeof window.setSelectedLocation==='function')window.setSelectedLocation(saved);const bind=(id,fn)=>{const el=document.getElementById(id);if(!el||el.dataset.locationFixBound==='1')return;el.dataset.locationFixBound='1';el.addEventListener('click',fn,{passive:false})};bind('locationButton',openModal);bind('locationBannerButton',openModal);bind('allowLocation',detect);bind('manualLocation',()=>document.getElementById('manualLocationBox')?.removeAttribute('hidden'));bind('saveManualLocation',()=>{const a=document.getElementById('manualLocationSelect')?.value;if(!a)return;setArea(a);localStorage.setItem('choPhuThoLocationSource','manual');closeModal();if(typeof window.applyHomeFilters==='function')window.applyHomeFilters()});document.querySelectorAll('[data-close-location]').forEach(el=>{if(el.dataset.locationFixBound==='1')return;el.dataset.locationFixBound='1';el.addEventListener('click',closeModal)});if(!saved&&document.getElementById('locationModal'))setTimeout(openModal,700)}
  window.initLocationExperience=init;
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init,{once:true});else init();
})();