// Chợ Phú Thọ - lớp hoàn thiện marketplace
(function(){
  const esc=v=>typeof escapeHtml==='function'?escapeHtml(v):String(v??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#039;','"':'&quot;'}[c]));
  const params=new URLSearchParams(location.search);
  function formatPrice(v){const n=Number(v);return n>0?n.toLocaleString('vi-VN')+' đ':'Thỏa thuận';}
  window.refreshFavoriteButtons=async function(){if(typeof supabaseClient==='undefined')return;const u=(await supabaseClient.auth.getUser()).data?.user;if(!u)return;const r=await supabaseClient.from('favorites').select('listing_id').eq('user_id',u.id);const ids=new Set((r.data||[]).map(x=>String(x.listing_id)));document.querySelectorAll('[data-favorite]').forEach(b=>b.textContent=ids.has(String(b.dataset.favorite))?'♥':'♡');};
  window.toggleFavorite=async function(id,button){if(typeof supabaseClient==='undefined')return;const u=(await supabaseClient.auth.getUser()).data?.user;if(!u){location.href='dang-nhap.html?next='+encodeURIComponent(location.pathname+location.search);return;}const q=await supabaseClient.from('favorites').select('id').eq('listing_id',id).eq('user_id',u.id).maybeSingle();if(q.error){alert('Không kiểm tra được tin yêu thích.');return;}if(q.data){const {error}=await supabaseClient.from('favorites').delete().eq('id',q.data.id);if(error){alert('Không thể bỏ lưu tin.');return;}button.textContent='♡';}else{const {error}=await supabaseClient.from('favorites').insert({listing_id:id,user_id:u.id});if(error){alert('Không thể lưu tin: '+error.message);return;}button.textContent='♥';}};
  function initUrlFilters(){const cat=params.get('category'),q=params.get('q')||params.get('search'),loc=params.get('location');if(cat&&document.getElementById('categoryFilter'))document.getElementById('categoryFilter').value=cat;if(q&&document.getElementById('searchInput'))document.getElementById('searchInput').value=q;if(loc&&document.getElementById('locationFilter'))document.getElementById('locationFilter').value=loc;if(cat||q||loc)window.setTimeout(()=>window.applyHomeFilters?.(),150);}
  function installMobileNav(){if(document.getElementById('mobileBottomNav'))return;const nav=document.createElement('nav');nav.id='mobileBottomNav';nav.className='mobile-bottom-nav';nav.setAttribute('aria-label','Điều hướng');nav.innerHTML='<a href="index.html" class="mobile-nav-item">⌂<span>Trang chủ</span></a><a href="quan-ly-tin.html" class="mobile-nav-item">▤<span>Quản lý tin</span></a><a href="dang-tin.html" class="mobile-nav-post">＋<span>Đăng tin</span></a><a href="chat.html" class="mobile-nav-item">◌<span>Tin nhắn</span></a><a href="tai-khoan.html" class="mobile-nav-item">◉<span>Tài khoản</span></a>';document.body.appendChild(nav);document.body.classList.add('has-mobile-bottom-nav');}
  function installMobileMenu(){const button=document.querySelector('.mobile-menu-button');if(!button||button.dataset.bound==='1')return;button.dataset.bound='1';if(!document.getElementById('mobile-menu-style')){const s=document.createElement('style');s.id='mobile-menu-style';s.textContent='#mobileMenuDrawer{position:fixed;inset:0;z-index:1000;pointer-events:none}#mobileMenuDrawer.open{pointer-events:auto}.mobile-menu-backdrop{position:absolute;inset:0;background:rgba(0,0,0,.38);opacity:0;transition:opacity .2s}.mobile-menu-panel{position:absolute;left:0;top:0;bottom:0;width:min(82vw,340px);background:#fff;padding:calc(14px + env(safe-area-inset-top)) 0 24px;box-shadow:8px 0 25px rgba(0,0,0,.16);transform:translateX(-105%);transition:transform .22s;overflow:auto}.mobile-menu-panel a{display:block;padding:15px 22px;border-bottom:1px solid #eee;color:#222;text-decoration:none;font-weight:700}.mobile-menu-head{display:flex;align-items:center;justify-content:space-between;padding:0 18px 16px;font-size:18px}.mobile-menu-head button{border:0;background:#f3f3f3;border-radius:50%;width:34px;height:34px;font-size:23px}.open .mobile-menu-backdrop{opacity:1}.open .mobile-menu-panel{transform:translateX(0)}';document.head.appendChild(s);}button.addEventListener('click',()=>{let drawer=document.getElementById('mobileMenuDrawer');if(drawer){drawer.classList.toggle('open');return;}drawer=document.createElement('aside');drawer.id='mobileMenuDrawer';drawer.innerHTML='<div class="mobile-menu-backdrop"></div><div class="mobile-menu-panel"><div class="mobile-menu-head"><strong>🛒 Chợ Phú Thọ</strong><button type="button" aria-label="Đóng">×</button></div><a href="index.html">🏠 Trang chủ</a><a href="danh-muc.html">📂 Tất cả danh mục</a><a href="yeu-thich.html">♡ Tin yêu thích</a><a href="chat.html">💬 Trao đổi online</a><a href="thong-bao.html">🔔 Thông báo</a><a href="quan-ly-tin.html">▤ Quản lý tin</a><a href="goi-dich-vu.html">⭐ Gói dịch vụ</a><a href="tai-khoan.html">👤 Tài khoản</a><a href="lien-he.html">☎ Liên hệ hỗ trợ</a></div>';document.body.appendChild(drawer);const close=()=>drawer.classList.remove('open');drawer.querySelector('.mobile-menu-backdrop').onclick=close;drawer.querySelector('button').onclick=close;drawer.querySelectorAll('a').forEach(a=>a.onclick=close);requestAnimationFrame(()=>drawer.classList.add('open'));});}
  document.addEventListener('DOMContentLoaded',()=>{initUrlFilters();const sort=document.getElementById('sortFilter');if(sort)sort.addEventListener('change',()=>{const list=[...(window.homeListings||[])];const mode=sort.value;if(mode==='price_asc')list.sort((a,b)=>Number(a.price||0)-Number(b.price||0));else if(mode==='price_desc')list.sort((a,b)=>Number(b.price||0)-Number(a.price||0));else if(mode==='views')list.sort((a,b)=>Number(b.view_count||0)-Number(a.view_count||0));else list.sort((a,b)=>new Date(b.created_at)-new Date(a.created_at));window.renderMarketplaceListings?.(list);});refreshFavoriteButtons();installMobileNav();installMobileMenu();});
  window.marketplaceFormatPrice=formatPrice;
})();