(function(){
  'use strict';
  const ROOT='/cho-phu-tho/';
  const $=(s,r=document)=>r.querySelector(s);
  const $$=(s,r=document)=>Array.from(r.querySelectorAll(s));
  window.ptToast=function(message){let el=$('.pt-toast');if(!el){el=document.createElement('div');el.className='pt-toast';document.body.appendChild(el)}el.textContent=message;el.classList.add('show');clearTimeout(window.__ptToastTimer);window.__ptToastTimer=setTimeout(()=>el.classList.remove('show'),2600)};
  function loading(show){let el=$('.pt-loading');if(!el){el=document.createElement('div');el.className='pt-loading';el.innerHTML='<div class="pt-spinner"></div>';document.body.appendChild(el)}el.classList.toggle('show',!!show)}
  window.ptLoading=loading;
  function getId(){return new URLSearchParams(location.search).get('id')||new URLSearchParams(location.search).get('listing');}
  async function user(){try{return (await supabaseClient.auth.getUser()).data.user}catch(e){return null}}
  async function notificationCount(){const u=await user();if(!u)return 0;let n=0,m=0;try{n=(await supabaseClient.from('notifications').select('id',{count:'exact',head:true}).eq('user_id',u.id).is('read_at',null)).count||0;m=(await supabaseClient.from('messages').select('id',{count:'exact',head:true}).eq('receiver_id',u.id).is('read_at',null)).count||0}catch(e){}return n+m}
  async function badges(){const count=await notificationCount();$$('a[href*="thong-bao"],a[href*="chat.html"],.notification-link').forEach(a=>{a.style.position='relative';let b=a.querySelector('.pt-notification-badge');if(count){if(!b){b=document.createElement('span');b.className='pt-notification-badge';a.appendChild(b)}b.textContent=count>99?'99+':count}else if(b)b.remove()})}
  function globalNav(){
    const nav=$('.mobile-bottom-nav');if(nav){nav.querySelectorAll('a').forEach(a=>{const href=a.getAttribute('href')||'';if(location.pathname.endsWith(href.replace('./','')))a.classList.add('active')})}
    if(!nav && innerWidth<=800){const n=document.createElement('nav');n.className='mobile-bottom-nav';n.setAttribute('aria-label','Điều hướng mobile');n.innerHTML='<a class="mobile-nav-item" href="index.html"><span class="mobile-nav-icon">⌂</span><span>Trang chủ</span></a><a class="mobile-nav-item" href="quan-ly-tin.html"><span class="mobile-nav-icon">▤</span><span>Quản lý tin</span></a><a class="mobile-nav-post" href="dang-tin.html"><span>＋</span><span>Đăng tin</span></a><a class="mobile-nav-item" href="chat.html"><span class="mobile-nav-icon">◌</span><span>Tin nhắn</span></a><a class="mobile-nav-item" href="tai-khoan.html"><span class="mobile-nav-icon">●</span><span>Tài khoản</span></a>';document.body.appendChild(n)}
  }
  async function recordView(){const id=getId();if(!id||!window.supabaseClient)return;const key='pt_view_'+id;const last=localStorage.getItem(key);const now=Date.now();if(last&&now-Number(last)<86400000)return;localStorage.setItem(key,String(now));try{const u=await user();await supabaseClient.from('listing_views').insert({listing_id:Number(id),viewer_id:u?.id||null,session_key:crypto.randomUUID?.()||String(Math.random()),viewed_on:new Date().toISOString().slice(0,10)}); }catch(e){}}
  function rememberRecent(){const id=getId();if(!id)return;let ids=[];try{ids=JSON.parse(localStorage.getItem('pt_recent_listings')||'[]')}catch(e){}ids=[String(id),...ids.filter(x=>String(x)!==String(id))].slice(0,8);localStorage.setItem('pt_recent_listings',JSON.stringify(ids))}
  async function shareListing(){const id=getId();if(!id)return;const url=location.href;try{if(navigator.share){await navigator.share({title:document.title,text:'Xem tin trên Chợ Phú Thọ',url});}else{await navigator.clipboard.writeText(url);ptToast('Đã sao chép liên kết tin đăng');}}catch(e){}}
  function injectShare(){if(!getId())return;if($('.pt-share-row'))return;const targets=$('.product-actions')||$('.detail-actions')||$('.listing-actions');if(!targets)return;const row=document.createElement('div');row.className='pt-share-row';row.innerHTML='<button type="button" class="pt-share-btn" data-pt-share>↗ Chia sẻ</button><button type="button" class="pt-share-btn" data-pt-copy>🔗 Sao chép link</button>';targets.parentNode?.insertBefore(row,targets.nextSibling);row.querySelector('[data-pt-share]').onclick=shareListing;row.querySelector('[data-pt-copy]').onclick=async()=>{try{await navigator.clipboard.writeText(location.href);ptToast('Đã sao chép link')}catch(e){ptToast('Không thể sao chép link')}}}
  async function contact(type){const id=getId();if(!id)return;const u=await user();if(!u){location.href='dang-nhap.html?next='+encodeURIComponent(location.pathname+location.search);return}try{const {data:l}=await supabaseClient.from('listings').select('seller_id').eq('id',Number(id)).maybeSingle();if(l?.seller_id&&l.seller_id!==u.id)await supabaseClient.rpc('record_seller_contact',{p_seller_id:l.seller_id,p_buyer_id:u.id,p_listing_id:Number(id),p_contact_type:type});}catch(e){}}
  function hookContacts(){const id=getId();if(!id)return;$$('a[href^="tel:"]').forEach(a=>a.addEventListener('click',()=>contact('phone')));$$('a[href*="zalo"]').forEach(a=>a.addEventListener('click',()=>contact('zalo')))}
  async function dynamicDetailMeta(){const id=getId();if(!id||!window.supabaseClient)return;try{const {data:l}=await supabaseClient.from('listings').select('id,title,description,price,location,category,slug').eq('id',Number(id)).maybeSingle();if(!l)return;document.title=(l.title||'Tin đăng')+' | Chợ Phú Thọ';let d=$('meta[name="description"]');if(!d){d=document.createElement('meta');d.name='description';document.head.appendChild(d)}d.content=(l.description||`${l.title||'Tin đăng'} tại ${l.location||'Phú Thọ'}`).slice(0,155);let c=$('link[rel="canonical"]');if(!c){c=document.createElement('link');c.rel='canonical';document.head.appendChild(c)}c.href=location.href.split('#')[0];const set=(p,v)=>{let e=$(`meta[property="${p}"]`);if(!e){e=document.createElement('meta');e.setAttribute('property',p);document.head.appendChild(e)}e.content=v};set('og:title',l.title||'Chợ Phú Thọ');set('og:description',d.content);set('og:url',location.href); }catch(e){}}
  function addRecentSection(){if(!location.pathname.endsWith('index.html')&&location.pathname!=='/cho-phu-tho/'&&location.pathname!=='/cho-phu-tho')return;if($('.pt-recent-section'))return;let ids=[];try{ids=JSON.parse(localStorage.getItem('pt_recent_listings')||'[]')}catch(e){}if(!ids.length)return;(async()=>{const {data}=await supabaseClient.from('listings').select('id,title,price,location,slug').in('id',ids.map(Number)).eq('status','approved');if(!data?.length)return;const sec=document.createElement('section');sec.className='pt-recent-section container';sec.innerHTML='<div class="pt-section-head"><h2>Tin bạn đã xem</h2><a href="javascript:void(0)" data-clear-recent>Xóa lịch sử</a></div><div class="pt-mini-grid"></div>';const grid=$('.pt-mini-grid',sec);data.sort((a,b)=>ids.indexOf(String(a.id))-ids.indexOf(String(b.id))).forEach(l=>{const a=document.createElement('a');a.className='pt-mini-card';a.href='chi-tiet.html?id='+l.id;a.innerHTML='<div class="pt-mini-body"><strong>'+escapeHtml(l.title||'Tin đăng')+'</strong><span>'+formatPrice(l.price)+'</span><small>'+escapeHtml(l.location||'Phú Thọ')+'</small></div>';grid.appendChild(a)});const main=$('main');if(main)main.appendChild(sec);sec.querySelector('[data-clear-recent]').onclick=()=>{localStorage.removeItem('pt_recent_listings');sec.remove();ptToast('Đã xóa lịch sử xem')}})()}
  function formatPrice(v){const n=Number(v||0);if(!n)return 'Thỏa thuận';return new Intl.NumberFormat('vi-VN').format(n)+' đ'}
  function escapeHtml(s){return String(s??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','\'':'&#39;','"':'&quot;'}[c]))}
  async function boot(){globalNav();badges();if(getId()){rememberRecent();recordView();injectShare();hookContacts();dynamicDetailMeta()}addRecentSection();setInterval(badges,20000)}
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot);else boot();
})();
